spring.application.name=asquare
server.port=${PORT:8082}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/asquare_laundry?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=never
