package com.laundry.main.payment.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.laundry.main.payment.enums.PaymentMethod;
import com.laundry.main.payment.enums.PaymentStatus;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@Schema(description = "Payment response payload")
public class PaymentResponse {

    @Schema(description = "Payment id", example = "1")
    private Long paymentId;

    @Schema(description = "Order id associated with this payment", example = "1")
    private Long orderId;

    @Schema(description = "Order number associated with this payment", example = "ORD-20260616143000")
    private String orderNumber;

    @Schema(description = "Payment reference generated by the system", example = "PAYREF-20260616-1234")
    private String paymentReference;

    @Schema(description = "Payment amount", example = "250.00")
    private BigDecimal paymentAmount;

    @Schema(description = "Payment method used", example = "CREDIT_CARD")
    private PaymentMethod paymentMethod;

    @Schema(description = "Current payment status", example = "COMPLETED")
    private PaymentStatus paymentStatus;

    @Schema(description = "External transaction identifier", example = "TXN123456789")
    private String transactionId;

    @Schema(description = "Any remarks associated with the payment", example = "Paid in full")
    private String remarks;

    @Schema(description = "Date and time when payment was processed", example = "2026-06-15T21:45:00")
    private LocalDateTime paymentDate;
}
